In [6]:
import numpy as np
import tensorflow  as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:

df=pd.read_csv("D:/Abhishek/Downloads/Insurance_data.csv")

In [8]:
df.head()

age  affordability  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordability']],df.bought_insurance,test_size=0.2,random_state=25)

In [10]:
len(X_train)

22

In [11]:
X_train_scaled=X_train.copy()#made copy of dataFrame
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()#made copy of dataFrame
X_test_scaled['age']=X_test_scaled['age']/100




In [12]:
X_train_scaled

age  affordability
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.62              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [ ]:
import time
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
start_time1 = time.time()

model.fit(X_train_scaled, y_train, epochs=5000)
end_time1 = time.time()


Epoch 1/5000


D:\Abhishek\demon\Apps\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 717ms/step - accuracy: 0.5455 - loss: 0.6437
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5455 - loss: 0.6434
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6432
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6429
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6426
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6424
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5455 - loss: 0.6421
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6418
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5455 - loss: 0.6416
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6413
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5455 - loss: 0.6410
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5455 - lo

In [39]:
# Get weights and bias from the single Dense layer
weights, bias = model.layers[0].get_weights()

print("Final weights:", weights.flatten())
print("Final bias:", bias)


Final weights: [5.770843  1.7468342]
Final bias: [-3.2005165]


In [41]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8333 - loss: 0.3412


[0.34119662642478943, 0.8333333134651184]

In [43]:
#train data is small and simple  can overfit with multi layer model but trains fast and accurate
import time
model2 = keras.Sequential([
    keras.Input(shape=(2,)),  # Input layer
    keras.layers.Dense(4, activation='relu'),  # Hidden layer
    keras.layers.Dense(1, activation='sigmoid')  # Output layer
])

model2.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
start_time2 = time.time()

model2.fit(X_train_scaled, y_train, epochs=500, verbose=1)
end_time2 = time.time()


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 764ms/step - accuracy: 0.5455 - loss: 0.6828
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5455 - loss: 0.6824
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6819
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5455 - loss: 0.6815
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6810
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5909 - loss: 0.6805
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5909 - loss: 0.6801
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5909 - loss: 0.6796
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6818 - loss: 0.6792
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6818 - loss: 0.6787
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6818 - loss: 0.6783
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6818 - l

In [44]:
# Layer 0: Dense(4, activation='relu')
weights_hidden, bias_hidden = model2.layers[0].get_weights()

# Layer 1: Dense(1, activation='sigmoid')
weights_output, bias_output = model2.layers[1].get_weights()


In [45]:
print("Hidden layer weights:\n", weights_hidden)
print("Hidden layer bias:\n", bias_hidden)
print("Output layer weights:\n", weights_output)
print("Output layer bias:\n", bias_output)


Hidden layer weights:
 [[-0.69564104 -0.87629175  0.6142578  -0.09444118]
 [-0.49791288  0.2195639   0.60494894  0.72360814]]
Hidden layer bias:
 [ 0.         -0.06906856 -0.17824501  0.02541699]
Output layer weights:
 [[-0.5209859 ]
 [ 0.39067012]
 [ 1.0175909 ]
 [ 1.1135366 ]]
Output layer bias:
 [-0.6192191]


In [46]:
model2.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.6667 - loss: 0.6227


[0.6226525902748108, 0.6666666865348816]

In [47]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [48]:
#single layer model
coef, intercept=model.get_weights()
coef, intercept

(array([[5.770843 ],
        [1.7468342]], dtype=float32),
 array([-3.2005165], dtype=float32))

In [49]:
print(f"Single-layer model training time: {end_time1 - start_time1:.2f} seconds")

Single-layer model training time: 286.24 seconds


In [50]:
print(f"Multi-layer model training time: {end_time2 - start_time2:.2f} seconds")

Multi-layer model training time: 27.55 seconds


In [51]:
#using function
import math
epsilon=1e-15
def logloss(y_predicted,y_true):
    total_error=0
    for yp,yt in zip(y_predicted,y_true):
     # Clip prediction to avoid log(0)
        yp=max(epsilon,min(yp,1-epsilon))
        total_error+=yt*math.log(yp)+(1-yt)*math.log(1-yp)
    logloss=-total_error/len(y_true)
    return logloss

In [52]:
import numpy as np

def sigmoid_numpy(x):
    return 1 / (1 + np.exp(-x))  

# Test with a NumPy array
sigmoid_numpy(np.array([12, 0, 1]))


array([0.99999386, 0.5       , 0.73105858])

In [76]:
#this code is for neural network in ml it was for linear regression or simple logistic regression
def gradient_descent(age,affordability,y_true,epochs,loss_thresold):
    #w1,w2,bias
    w1=0
    w2=0
    bias=-3
    rate=0.5
    n=len(age)
    for i in range(epochs):
        weighted_sum=w1*age+w2*affordability+bias#this is just  linear regression
        y_predicted=sigmoid_numpy(weighted_sum)# this is just sigmoid
        loss=logloss(y_predicted,y_true)
        #Gradient calculation
        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))#Gradient computed with respect to corresponding feature
        bias_d=np.mean(y_predicted-y_true)

        w1=w1-rate*w1d
        w2=w2-rate*w2d
        print(f'Epoch: {i},w1:{w1},w2:{w2}, bias:{bias}, loss{loss}')
        if loss<=loss_thresold:#to stop when loss is same as tensorflow function to compare weights
            break
    return w1,w2,bias         

#transpose 
age=[20,]    to age =[20,30,40]
    [30,]
    [40]

#dot product
[20,30,40]X[−0.10.2−0.2]=(20x−0.1)+(30X0.2)+(40X-0.2)=-4

In [78]:
#calling the function on numpy vector
gradient_descent(X_train_scaled['age'],X_train_scaled['affordability'],y_train,1000,   0.4994)

Epoch: 0,w1:0.1295743206016999,w2:0.21218267671622876, bias:-3, loss1.684950987937379
Epoch: 1,w1:0.2570087330419345,w2:0.41999257139113244, bias:-3, loss1.562486142430104
Epoch: 2,w1:0.3818109232247536,w2:0.6223818056309895, bias:-3, loss1.445043849801439
Epoch: 3,w1:0.5034303910947633,w2:0.8181805807928816, bias:-3, loss1.3336398363098734
Epoch: 4,w1:0.6212832032040767,w2:1.0061494220517688, bias:-3, loss1.2293097470067378
Epoch: 5,w1:0.7347903932640633,w2:1.1850594989977794, bias:-3, loss1.1330173998474087
Epoch: 6,w1:0.843426216954275,w2:1.3537931191448882, bias:-3, loss1.0455456775341818
Epoch: 7,w1:0.9467677216610508,w2:1.5114468746921073, bias:-3, loss0.9673925481560186
Epoch: 8,w1:1.0445344741059897,w2:1.65741462831907, bias:-3, loss0.8987002675458111
Epoch: 9,w1:1.1366089795807852,w2:1.7914309214832067, bias:-3, loss0.8392395974321555
Epoch: 10,w1:1.223034108323741,w2:1.9135670657775503, bias:-3, loss0.7884535492202321
Epoch: 11,w1:1.3039908130633706,w2:2.0241863401730913, bia

(2.7221209847736283, 2.842705013545896, -3)

In [80]:
#coef of single layer model
coef,intercept

(array([[5.770843 ],
        [1.7468342]], dtype=float32),
 array([-3.2005165], dtype=float32))

In [ ]:
#This shows that we are able to replicate what Tensorflow did internally using our plain python code
